apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard