studySpec:
  metrics:
  - metricId: mse
    goal: MINIMIZE
  parameters:
  - parameterId: n_estimators
    integerValueSpec:
      minValue: 100
      maxValue: 150
trialJobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
      replicaCount: 1
      containerSpec:
        imageUri: gcr.io/ml-ops-439823/train-model
