name: Add Deploy Details

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'deploy_details.json'     # Triggers when JSON files change

permissions:
  contents: write
  pull-requests: write

jobs:
  add-deploy-details:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create new branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          branch_name="update-deploy-details-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $branch_name
          
      - name: Update deploy details file
        run: |
          echo '{
            "old_model": {
              "mse": 0.001,
              "version": "v0.1.0_eef246ea",
              "uri": "pvc://model-storage//mnt/models/random_forest_model_20241027_064949_15275863.joblib"
            },
            "new_model": {
              "mse": 0.001,
              "version": "v0.1.0_46c6ef63",
              "uri": "random_forest_model_20241027_114116_dc0a6d32.joblib"
            }
          }' > deploy_details.json
          
      - name: Commit and push changes
        run: |
          git add deploy_details.json
          git commit -m "Update deploy details JSON file"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update deploy details JSON file
          title: 'Update Deploy Details JSON'
          body: |
            Automated PR to update deploy_details.json
            - Updated model deployment details
            - Generated by GitHub Action
          branch: ${{ env.branch_name }}
          base: main
          delete-branch: true